on:
    push:
        branches:
        - master
    pull_request:
        branches:
        - master
jobs:
    unit-test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up Go 1.15
          uses: actions/setup-go@v2
          with:
            go-version: 1.15
        - name: Build
          working-directory: src
          run: go build -v ./...
        - name: Test
          working-directory: src
          run: go test -v ./...
    integration-test:
      needs:
        - unit-test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Test with gcs-client-tester
          run: |
            docker-compose -f integration-tests/docker-compose.yml up --build --exit-code-from gcs-client-tester
            docker-compose -f integration-tests/docker-compose.yml down --remove-orphans --volumes
        - name: Fail if gcs-client-tester failed
          run: |
            if [ $? -ne 0 ]; then
              exit 1
            fi